include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**

linter:
  rules:
    - prefer_relative_imports
    - unnecessary_breaks
    - prefer_const_constructors
    - public_member_api_docs
