// Copyright (C) 2026 Fiber
//
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at https://mozilla.org/MPL/2.0/.
//
// What you may do:
// - Use this software for any purpose, including commercially, and build and
//   sell your own products on top of it.
// - Change it, and create new works based on it.
// - Distribute copies of it, with or without your changes.
// - Combine it with files under any other licence, proprietary ones included,
//   and licence that larger work on your own terms.
//
// What you must do in return:
// - Keep this notice on every file you received it on.
// - Publish, under these same terms, the source of every file covered by them
//   that you distribute, including the ones you changed, so that whoever
//   receives your version can obtain that source.
// - Leave Fiber out of it: the name "Fiber", its branding, its logos and its
//   trademarks may not be used to endorse or promote what you build, and this
//   licence grants no right to them.
//
// Disclaimer:
// AS FAR AS THE LAW ALLOWS, THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
// OR CONDITION OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
// NON-INFRINGEMENT. IN NO EVENT SHALL FIBER BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT
// LIMITED TO LOSS OF USE, DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING OUT
// OF OR RELATED TO THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY
// KIND OF LEGAL CLAIM.
//
// This header is a summary written for convenience. Where it differs from the
// LICENSE file, the LICENSE file governs.

import 'dart:convert';

import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:rxdart/rxdart.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../common/observable.dart';
import '../common/reporter.dart';

/// The default `toJson` for [Preference.list_]: passes the value through as is.
Object? _identityJson(Object? value) => value;

/// A project's own local preferences, read and written straight through
/// `shared_preferences`'s native types.
///
/// [PreferencesStorage] itself is registered `@Singleton(order: -1)`, resolved
/// the moment a project's own `configureSdk` (generated by
/// `injectable`) runs:
///
/// ```dart
/// @InjectableInit()
/// Future<void> configureSdk() => GetIt.instance.init();
/// ```
///
/// From then on, a project declares one entry per setting anywhere, through
/// whichever of [PreferencesStorage]'s own static factories matches the stored
/// type — [int_], [bool_], [double_], [string_], [list_], [enum_] or
/// [json_] — without holding a [PreferencesStorage] reference of its own:
///
/// ```dart
/// class AppPreferences {
///   late final themeMode = PreferencesStorage.enum_(
///     'theme_mode',
///     ThemeMode.values,
///     ThemeMode.system,
///   );
///   late final vibrations = PreferencesStorage.bool_('vibrations', true);
/// }
/// ```
///
/// `AppPreferences` itself is a plain class here: registering it as its own
/// singleton — `@singleton`, or a plain `GetIt.instance.registerSingleton`
/// call — is a separate decision, since [PreferencesStorage]'s own factories
/// already reach the registered instance on their own. A backend that keeps
/// a credential through `StoredCredential` can rely on [PreferencesStorage]
/// already being resolved by the time its own `initialize` runs, since
/// `order: -1` resolves it ahead of anything that depends on it.
@Singleton(order: -1)
class PreferencesStorage {
  late final SharedPreferences _prefs;

  /// Resolves the [PreferencesStorage] `configureSdk` registers.
  ///
  /// Marked [FactoryMethod.preResolve] so `configureSdk` awaits it
  /// before registering the result, rather than handing out a half-resolved
  /// instance.
  @FactoryMethod(preResolve: true)
  static Future<PreferencesStorage> initialize() async {
    final service = PreferencesStorage();
    service._prefs = await SharedPreferences.getInstance();
    return service;
  }

  static PreferencesStorage get _instance => GetIt.instance<PreferencesStorage>();

  /// An entry holding an [int], on the registered [PreferencesStorage].
  static Preference<int> int_(String key, int defaultValue) => Preference.int_(_instance, key, defaultValue);

  /// An entry holding a [bool], on the registered [PreferencesStorage].
  static Preference<bool> bool_(String key, bool defaultValue) => Preference.bool_(_instance, key, defaultValue);

  /// An entry holding a [double], on the registered [PreferencesStorage].
  static Preference<double> double_(String key, double defaultValue) => Preference.double_(_instance, key, defaultValue);

  /// An entry holding a [String], on the registered [PreferencesStorage].
  static Preference<String> string_(String key, String defaultValue) => Preference.string_(_instance, key, defaultValue);

  /// An entry holding a list of [L], JSON-encoded, on the registered
  /// [PreferencesStorage]. See [Preference.list_] for [toJson].
  static Preference<List<L>> list_<L>(
    String key,
    List<L> defaultValue,
    L Function(dynamic json) fromJson, {
    Object? Function(L value) toJson = _identityJson,
    Reporter reporter = const SilentReporter(),
  }) => Preference.list_<L>(_instance, key, defaultValue, fromJson, toJson: toJson, reporter: reporter);

  /// An entry holding one member of [E], on the registered [PreferencesStorage].
  static Preference<E> enum_<E extends Enum>(String key, List<E> values, E defaultValue) =>
      Preference.enum_(_instance, key, values, defaultValue);

  /// An entry holding one [J], JSON-encoded, on the registered
  /// [PreferencesStorage].
  static Preference<J> json_<J extends PreferenceJson?>(
    String key,
    J defaultValue,
    J Function(Map<String, dynamic> json) fromJson, {
    Reporter reporter = const SilentReporter(),
  }) => Preference.json_<J>(_instance, key, defaultValue, fromJson, reporter: reporter);
}

/// One entry of a [PreferencesStorage], read and written in whichever native
/// type `shared_preferences` already stores it as.
///
/// Never constructed directly: [int_], [bool_], [double_], [string_],
/// [list_], [enum_] and [json_] are the only ways to declare one, each
/// fixing which shape it reads and writes so a project never has to name (or
/// get wrong) the private class actually backing it.
sealed class Preference<T> extends Observable<T> {
  final PreferencesStorage _preferences;
  final String _key;
  final T _defaultValue;

  /// Seeded once, lazily, from [_fetch] — the moment something first reads
  /// [value], [call] or [stream], not before, so the read never runs ahead
  /// of a subclass's own fields still being set.
  late final BehaviorSubject<T> _valueSubject = BehaviorSubject<T>.seeded(_fetch());

  Preference._(this._preferences, this._key, this._defaultValue);

  /// An entry holding an [int].
  static Preference<int> int_(PreferencesStorage service, String key, int defaultValue) =>
      _PreferencePrimitive<int>(service, key, defaultValue);

  /// An entry holding a [bool].
  static Preference<bool> bool_(PreferencesStorage service, String key, bool defaultValue) =>
      _PreferencePrimitive<bool>(service, key, defaultValue);

  /// An entry holding a [double].
  static Preference<double> double_(PreferencesStorage service, String key, double defaultValue) =>
      _PreferencePrimitive<double>(service, key, defaultValue);

  /// An entry holding a [String].
  static Preference<String> string_(PreferencesStorage service, String key, String defaultValue) =>
      _PreferencePrimitive<String>(service, key, defaultValue);

  /// An entry holding a list of [L], JSON-encoded as a whole.
  ///
  /// `shared_preferences` has no native list type beyond a [List] of
  /// [String], so a list of anything else is JSON-encoded under one key
  /// instead, the same way [json_] encodes a single value. [toJson] defaults
  /// to passing each element through as is, which is enough when [L] is
  /// already one of `jsonEncode`'s own native types; give it explicitly for
  /// anything else, such as a [PreferenceJson].
  ///
  /// A stored value that no longer decodes is reported and answered with
  /// [defaultValue], never thrown, since this is read during startup.
  static Preference<List<L>> list_<L>(
    PreferencesStorage service,
    String key,
    List<L> defaultValue,
    L Function(dynamic json) fromJson, {
    Object? Function(L value) toJson = _identityJson,
    Reporter reporter = const SilentReporter(),
  }) => _PreferenceJsonList<L>(service, key, defaultValue, fromJson, toJson, reporter: reporter);

  /// An entry holding one member of [E], stored by name rather than by
  /// index, so reordering the enum does not silently change what every
  /// existing installation reads back.
  static Preference<E> enum_<E extends Enum>(PreferencesStorage service, String key, List<E> values, E defaultValue) =>
      _PreferenceEnum<E>(service, key, values, defaultValue);

  /// An entry holding one [J], JSON-encoded.
  ///
  /// A stored value that no longer decodes is reported and answered with
  /// [defaultValue], never thrown, since this is read during startup.
  static Preference<J> json_<J extends PreferenceJson?>(
    PreferencesStorage service,
    String key,
    J defaultValue,
    J Function(Map<String, dynamic> json) fromJson, {
    Reporter reporter = const SilentReporter(),
  }) => _PreferenceJsonClass<J>(service, key, defaultValue, fromJson, reporter: reporter);

  /// The key this entry occupies in `shared_preferences`.
  String get key => _key;

  /// What answers a key nothing has written to yet.
  T get defaultValue => _defaultValue;

  @override
  T get value => _valueSubject.value;

  /// The current value, same as [value] — lets an entry be read by calling
  /// it directly, `vibrations()` rather than `vibrations.value`.
  T call() => _valueSubject.value;

  /// Unlike [Observable.stream]'s own contract, this replays the current
  /// value to every new listener before anything that changes after: it is
  /// backed by a [BehaviorSubject], which always does.
  @override
  Stream<T> get stream => _valueSubject.stream;

  /// Same as [stream]: already the current value followed by every change,
  /// so [Observable.values]'s own way of building that — replaying [value]
  /// by hand, then listening to [stream] — would publish the current value
  /// twice.
  @override
  Stream<T> get values => stream;

  /// Reads this entry straight out of `shared_preferences`, decoding it into
  /// [T] however this shape does that. Runs exactly once, to seed
  /// [_valueSubject]: every read after that answers from the cache instead,
  /// kept in step by [set].
  T _fetch();

  /// Stores [next], caches it, and publishes it on [stream].
  ///
  /// Ignored when [next] already equals [value], except for a [List]: two
  /// lists that compare unequal by identity can still hold the same
  /// elements, and a caller that mutated one in place expects the write to
  /// happen regardless.
  Future<void> set(T next) async {
    if (next is! List && next == value) return;

    final prefs = _preferences._prefs;
    switch (next) {
      case null:
        await prefs.remove(_key);
      case final bool v:
        await prefs.setBool(_key, v);
      case final int v:
        await prefs.setInt(_key, v);
      case final double v:
        await prefs.setDouble(_key, v);
      case final String v:
        await prefs.setString(_key, v);
      case final List<String> v:
        await prefs.setStringList(_key, v);
      case final Enum v:
        await prefs.setString(_key, v.name);
      case final PreferenceJson v:
        await prefs.setString(_key, jsonEncode(v.toJson()));
      default:
        throw ArgumentError.value(next, 'next', 'not a storable type');
    }

    if (!_valueSubject.isClosed) _valueSubject.add(next);
  }

  /// Removes the stored value and publishes [defaultValue] on [stream].
  Future<void> clear() => set(_defaultValue);

  /// Closes [stream] for every listener.
  Future<void> dispose() => _valueSubject.close();
}

/// The [Preference] behind [Preference.int_], [Preference.bool_], [Preference.double_]
/// and [Preference.string_]: whichever native type `shared_preferences` already
/// stores [T] as, read back as is.
final class _PreferencePrimitive<T> extends Preference<T> {
  _PreferencePrimitive(super.service, super.key, super.defaultValue) : super._();

  @override
  T _fetch() {
    final savedValue = _preferences._prefs.get(key);
    if (savedValue is List<Object?>) {
      final strings = savedValue.whereType<String>().toList();
      return strings is T ? strings as T : defaultValue;
    }
    return savedValue is T ? savedValue : defaultValue;
  }
}

/// The [Preference] behind [Preference.enum_].
final class _PreferenceEnum<T extends Enum> extends Preference<T> {
  final List<T> _values;

  _PreferenceEnum(PreferencesStorage service, String key, this._values, T defaultValue) : super._(service, key, defaultValue);

  @override
  T _fetch() {
    final stored = _preferences._prefs.getString(key);
    return _values.asNameMap()[stored] ?? defaultValue;
  }
}

/// The [Preference] behind [Preference.json_].
final class _PreferenceJsonClass<T extends PreferenceJson?> extends Preference<T> {
  final T Function(Map<String, dynamic> json) _fromJson;
  final Reporter _reporter;

  _PreferenceJsonClass(
    super.service,
    super.key,
    super.defaultValue,
    this._fromJson, {
    Reporter reporter = const SilentReporter(),
  }) : _reporter = reporter,
       super._();

  @override
  T _fetch() {
    final stored = _preferences._prefs.getString(key);
    if (stored == null) return defaultValue;
    try {
      return _fromJson(jsonDecode(stored) as Map<String, dynamic>);
    } catch (error, stackTrace) {
      _reporter.recordError(error, stackTrace, context: {'preference': key});
      return defaultValue;
    }
  }
}

/// The [Preference] behind [Preference.list_].
///
/// Stores the whole list as one JSON-encoded string, since
/// `shared_preferences` has no native list type beyond [String]: [set]
/// therefore never reaches [Preference.set]'s own switch, which would refuse
/// anything but a `List<String>`.
final class _PreferenceJsonList<T> extends Preference<List<T>> {
  final T Function(dynamic json) _fromJson;
  final Object? Function(T value) _toJson;
  final Reporter _reporter;

  _PreferenceJsonList(
    super.service,
    super.key,
    super.defaultValue,
    this._fromJson,
    this._toJson, {
    Reporter reporter = const SilentReporter(),
  }) : _reporter = reporter,
       super._();

  @override
  List<T> _fetch() {
    final stored = _preferences._prefs.getString(key);
    if (stored == null) return defaultValue;
    try {
      return (jsonDecode(stored) as List<dynamic>).map(_fromJson).toList();
    } catch (error, stackTrace) {
      _reporter.recordError(error, stackTrace, context: {'preference': key});
      return defaultValue;
    }
  }

  @override
  Future<void> set(List<T> next) async {
    await _preferences._prefs.setString(key, jsonEncode(next.map(_toJson).toList()));
    if (!_valueSubject.isClosed) _valueSubject.add(next);
  }
}

/// A value [Preference.json_] can store, JSON-encoded.
abstract class PreferenceJson {
  /// This value as JSON, in the shape a project's own `fromJson` rebuilds
  /// from.
  Map<String, dynamic> toJson();
}